FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install \
    curl \
    git \
    libxcb-cursor0 \
    python3-pip \
    python3-venv \
    ubuntu-gnome-desktop \
    -y
